####################################################################################################
## 공용
####################################################################################################
spring:
  profiles:
    active: local
  application:
    name: downloader

server:
  port: 8880


---
####################################################################################################
## local
####################################################################################################
spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8085

    producer:
      topic: download-product
      acks: -1

    consumer:
      topic: download-target
      group-id: reactive_consumer_group
      enable-auto-commit: false
      auto-commit-interval: 10
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

---

####################################################################################################
## dev
####################################################################################################
spring:
  config:
    activate:
      on-profile: dev

---

####################################################################################################
## live
####################################################################################################
spring:
  config:
    activate:
      on-profile: prod
